# Generated by Django 3.1.4 on 2020-12-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('service_id', models.CharField(blank=True, max_length=30, null=True)),
                ('trip_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('trip_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('trip_headsign', models.CharField(blank=True, max_length=100, null=True)),
                ('direction_id', models.SmallIntegerField(blank=True, null=True)),
                ('block_id', models.IntegerField(blank=True, null=True)),
                ('shape_id', models.CharField(blank=True, max_length=20, null=True)),
                ('bikes_allowed', models.SmallIntegerField(blank=True, null=True)),
                ('wheelchair_accessible', models.SmallIntegerField(blank=True, null=True)),
                ('trip_type', models.IntegerField(blank=True, null=True)),
                ('drt_max_travel_time', models.IntegerField(blank=True, null=True)),
                ('drt_avg_travel_time', models.IntegerField(blank=True, null=True)),
                ('drt_advance_book_min', models.IntegerField(blank=True, null=True)),
                ('drt_pickup_message', models.IntegerField(blank=True, null=True)),
                ('drt_drop_off_message', models.IntegerField(blank=True, null=True)),
                ('continuous_pickup_message', models.CharField(blank=True, max_length=50, null=True)),
                ('continuous_drop_off_message', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'trips',
                'db_table': 'trips',
                'managed': False,
            },
        ),
    ]
