# Generated by Django 3.1.4 on 2020-12-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agency_url', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_lang', models.CharField(blank=True, max_length=10, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('agency_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('agency_fare_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'db_table': 'agency',
                'managed': False,
            },
        ),
    ]
