# Generated by Django 3.1.4 on 2020-12-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agency_url', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_lang', models.CharField(blank=True, max_length=10, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('agency_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('agency_fare_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'db_table': 'agency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('route_long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('route_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('route_type', models.SmallIntegerField(blank=True, null=True)),
                ('route_url', models.CharField(blank=True, max_length=50, null=True)),
                ('route_color', models.CharField(blank=True, max_length=11, null=True)),
                ('route_text_color', models.CharField(blank=True, max_length=11, null=True)),
                ('route_sort_order', models.IntegerField(blank=True, null=True)),
                ('min_headway_minutes', models.IntegerField(blank=True, null=True)),
                ('eligibility_restricted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'routes',
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('shape_id_serial', models.AutoField(primary_key=True, serialize=False)),
                ('shape_id', models.CharField(max_length=50)),
                ('shape_pt_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('shape_pt_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('shape_pt_sequence', models.IntegerField(blank=True, null=True)),
                ('shape_dist_traveled', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'shapes',
                'db_table': 'shapes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_code', models.CharField(blank=True, max_length=10, null=True)),
                ('platform_code', models.CharField(blank=True, max_length=10, null=True)),
                ('stop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('stop_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('zone_id', models.IntegerField(blank=True, null=True)),
                ('stop_url', models.CharField(blank=True, max_length=50, null=True)),
                ('location_type', models.SmallIntegerField(blank=True, null=True)),
                ('parent_station', models.IntegerField(blank=True, null=True)),
                ('stop_timezone', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('direction_id', models.IntegerField(blank=True, null=True)),
                ('wheelchair_boarding', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'stops',
                'db_table': 'stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('arrival_time', models.CharField(blank=True, max_length=8, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=8, null=True)),
                ('stop_sequence', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_headsign', models.CharField(blank=True, max_length=20, null=True)),
                ('pickup_type', models.SmallIntegerField(blank=True, null=True)),
                ('drop_off_type', models.SmallIntegerField(blank=True, null=True)),
                ('shape_dist_traveled', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('timepoint', models.SmallIntegerField(blank=True, null=True)),
                ('start_service_area_id', models.CharField(blank=True, max_length=11, null=True)),
                ('end_service_area_id', models.CharField(blank=True, max_length=11, null=True)),
                ('start_service_area_radius', models.CharField(blank=True, max_length=11, null=True)),
                ('end_service_area_radius', models.CharField(blank=True, max_length=11, null=True)),
                ('continuous_pickup', models.CharField(blank=True, max_length=11, null=True)),
                ('continuous_drop_off', models.CharField(blank=True, max_length=11, null=True)),
                ('pickup_area_id', models.CharField(blank=True, max_length=11, null=True)),
                ('drop_off_area_id', models.CharField(blank=True, max_length=11, null=True)),
                ('pickup_service_area_radius', models.CharField(blank=True, max_length=11, null=True)),
                ('drop_off_service_area_radius', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name_plural': 'stop_times',
                'db_table': 'stop_times',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('service_id', models.CharField(blank=True, max_length=30, null=True)),
                ('trip_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('trip_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('trip_headsign', models.CharField(blank=True, max_length=100, null=True)),
                ('direction_id', models.SmallIntegerField(blank=True, null=True)),
                ('block_id', models.IntegerField(blank=True, null=True)),
                ('shape_id', models.CharField(blank=True, max_length=20, null=True)),
                ('bikes_allowed', models.SmallIntegerField(blank=True, null=True)),
                ('wheelchair_accessible', models.SmallIntegerField(blank=True, null=True)),
                ('trip_type', models.IntegerField(blank=True, null=True)),
                ('drt_max_travel_time', models.IntegerField(blank=True, null=True)),
                ('drt_avg_travel_time', models.IntegerField(blank=True, null=True)),
                ('drt_advance_book_min', models.IntegerField(blank=True, null=True)),
                ('drt_pickup_message', models.IntegerField(blank=True, null=True)),
                ('drt_drop_off_message', models.IntegerField(blank=True, null=True)),
                ('continuous_pickup_message', models.CharField(blank=True, max_length=50, null=True)),
                ('continuous_drop_off_message', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'trips',
                'db_table': 'trips',
                'managed': False,
            },
        ),
    ]
