# Generated by Django 3.1.4 on 2020-12-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('arrival_time', models.CharField(blank=True, max_length=8, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=8, null=True)),
                ('stop_sequence', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_headsign', models.CharField(blank=True, max_length=20, null=True)),
                ('pickup_type', models.SmallIntegerField(blank=True, null=True)),
                ('drop_off_type', models.SmallIntegerField(blank=True, null=True)),
                ('shape_dist_traveled', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('timepoint', models.SmallIntegerField(blank=True, null=True)),
                ('start_service_area_id', models.CharField(blank=True, max_length=11, null=True)),
                ('end_service_area_id', models.CharField(blank=True, max_length=11, null=True)),
                ('start_service_area_radius', models.CharField(blank=True, max_length=11, null=True)),
                ('end_service_area_radius', models.CharField(blank=True, max_length=11, null=True)),
                ('continuous_pickup', models.CharField(blank=True, max_length=11, null=True)),
                ('continuous_drop_off', models.CharField(blank=True, max_length=11, null=True)),
                ('pickup_area_id', models.CharField(blank=True, max_length=11, null=True)),
                ('drop_off_area_id', models.CharField(blank=True, max_length=11, null=True)),
                ('pickup_service_area_radius', models.CharField(blank=True, max_length=11, null=True)),
                ('drop_off_service_area_radius', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name_plural': 'stop_times',
                'db_table': 'stop_times',
                'managed': False,
            },
        ),
    ]
