# Generated by Django 3.1.4 on 2020-12-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_code', models.CharField(blank=True, max_length=10, null=True)),
                ('platform_code', models.CharField(blank=True, max_length=10, null=True)),
                ('stop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('stop_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('zone_id', models.IntegerField(blank=True, null=True)),
                ('stop_url', models.CharField(blank=True, max_length=50, null=True)),
                ('location_type', models.SmallIntegerField(blank=True, null=True)),
                ('parent_station', models.IntegerField(blank=True, null=True)),
                ('stop_timezone', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('direction_id', models.IntegerField(blank=True, null=True)),
                ('wheelchair_boarding', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'stops',
                'db_table': 'stops',
                'managed': False,
            },
        ),
    ]
